add new join our team page
ChingChang9/PlantForever pull request #16
Opened 2021-12-18 08:47 UTC by ChingChang9

![image](https://user-images.githubusercontent.com/38874004/146635307-0476549d-0a35-4258-b608-5554a7e4ae27.jpeg)
![image](https://user-images.githubusercontent.com/38874004/146635285-e5f780de-b765-4f57-aaf3-586f320a35dc.jpeg)
![image](https://user-images.githubusercontent.com/38874004/146635289-d44c9af9-749f-4b89-a284-3b6ac1fa1dba.jpeg)

2021-12-18 22:07 UTC, marmikpatel19 commented on src/views/Volunteer.vue
> +				Want to do more than just planing trees? Consider <router-link :to="{ name: 'JoinTeam' }">joining our team</router-link>!
Since our Operations position includes planting trees, I'm not sure if "want to do more than just planting trees" is accurate. Maybe we can change this to "Want to do more than basic volunteer?" What do you think?

2021-12-18 22:10 UTC, marmikpatel19 commented on src/views/JoinTeam.vue
> +      <div>Disclaimer: All positions at PlantForever are currently volunteer-based</div>
Can we add a line of space between the disclaimer and the first position? I feel like it would look a little bit nicer :)

2021-12-18 22:10 UTC, marmikpatel19 commented on src/views/JoinTeam.vue
> +
See VP Finance position comment on the meeting doc

2021-12-18 22:11 UTC, marmikpatel19 commented on src/views/JoinTeam.vue
> +          <li>Overlooks PlantForever’s social media accounts</li>
You're right! Let's make this "Oversees"

2021-12-18 22:12 UTC, marmikpatel19 commented on src/views/JoinTeam.vue
> +      <div>Disclaimer: All positions at PlantForever are currently volunteer-based</div>
A line of space between each position would be nice as well. What do you think?

2021-12-18 22:14 UTC, marmikpatel19 requested changes
Thanks for the changes, Ching! I left some minor comments on a few of the files as well as our meeting doc :)

2021-12-19 06:22 UTC, ChingChang9 commented
Fixed the changes you mentioned and here's a preview of the page ![image](https://user-images.githubusercontent.com/38874004/146666011-7f1a9a84-66f0-46ee-b3c0-c6547fe6356f.jpeg)

2021-12-19 17:55 UTC, marmikpatel19 approved these changes

2021-12-19 17:56 UTC, merged